<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de errores</title>
</head>
<body>
    <script>
        // callbacks
        function sumar(numero1, numero2, callback){
            setTimeout(function(){
                if(typeof numero1 != 'number' || typeof numero2 != 'number'){
                    return callback( new Error('Algun argumento no es número'))
                }
                callback(null, numero1 + numero2) // null es para el error... y lo otro es para el resultado
            }, 1000)
        }
        sumar(20, 50, function(error, resultado){
            if(error){
                console.log(error)
            } else{
                console.log(resultado)
            }
        });

        // promesas 
        function sumar1(numero1, numero2){
            return new Promise(function(resolve, reject){
                setTimeout(function(){
                if(typeof numero1 != 'number' || typeof numero2 != 'number'){
                    reject('Ambos argumentos deben ser números')
                } else {
                    resolve(numero1 + numero2)
                }
            }, 1000)
            })
            
        }
        sumar1(20, 50)
            .then(function(resultado){
                console.log(resultado)
            }).catch(function(error){
                console.log(error)
            })

        // async await 
       async function sumar2(numero1, numero2){
           if(typeof numero1 != 'number' || typeof numero2 != 'number'){
            throw new Error('Alguno de los argumentos no es un número')
           }
           return numero1 + numero2
        }
        async function manejoErrores(){
            try {
                
            } catch (error) {
                
            }
        }
        sumar(20, 50);
    </script>
</body>
</html>